dotenv: .env

networks:
  #default: development
  mainnet-fork:
    eth_usd_price_feed_address: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  kovan:
    eth_usd_price_feed_address: "0x9326BFA02ADD2366b30bacB125260Af641031331"
    verify: False
  rinkeby:
    eth_usd_price_feed_address: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
  development:
    my_var: "0x"
  ganache-local:
    my_var: "0x"

wallets:
  from_key: ${PRIVATE_KEY}

dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink@1.3.0

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink@1.3.0'